### ISSUE TITLE
IllegalStateException: There are multiple DataStores active for the same file

### ISSUE THREAD

**Issue by wba2hi** [eclipse-kuksa/kuksa-android-sdk#81]
Functional:
- open app (fresh deploy) -> return to home screen via back swipe -> crash 
```
java.lang.IllegalStateException: There are multiple DataStores active for the same file: /data/user/0/org.eclipse.kuksa.testapp/files/datastore/connection_info. You should either maintain your DataStore as a singleton or confirm that there is no two DataStore's active on the same file (by confirming that the scope is cancelled).
                                                                                                    	at androidx.datastore.core.SingleProcessDataStore$file$2.invoke(SingleProcessDataStore.kt:168)
                                                                                                    	at androidx.datastore.core.SingleProcessDataStore$file$2.invoke(SingleProcessDataStore.kt:163)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at androidx.datastore.core.SingleProcessDataStore.getFile(SingleProcessDataStore.kt:163)
                                                                                                    	at androidx.datastore.core.SingleProcessDataStore.readData(SingleProcessDataStore.kt:380)
                                                                                                    	at androidx.datastore.core.SingleProcessDataStore.readDataOrHandleCorruption(SingleProcessDataStore.kt:359)
                                                                                                    	at androidx.datastore.core.SingleProcessDataStore.readAndInit(SingleProcessDataStore.kt:322)
                                                                                                    	at androidx.datastore.core.SingleProcessDataStore.readAndInitOrPropagateFailure(SingleProcessDataStore.kt:311)
                                                                                                    	at androidx.datastore.core.SingleProcessDataStore.handleRead(SingleProcessDataStore.kt:261)
                                                                                                    	at androidx.datastore.core.SingleProcessDataStore.access$handleRead(SingleProcessDataStore.kt:76)
                                                                                                    	at androidx.datastore.core.SingleProcessDataStore$actor$3.invokeSuspend(SingleProcessDataStore.kt:239)
                                                                                                    	at androidx.datastore.core.SingleProcessDataStore$actor$3.invoke(Unknown Source:8)
                                                                                                    	at androidx.datastore.core.SingleProcessDataStore$actor$3.invoke(Unknown Source:4)
                                                                                                    	at androidx.datastore.core.SimpleActor$offer$2.invokeSuspend(SimpleActor.kt:122)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@a5b1c35, androidx.compose.runtime.BroadcastFrameClock@16158ca, StandaloneCoroutine{Cancelling}@5bc8a3b, AndroidUiDispatcher@8070558]
```

_Originally posted by @Chrylo in https://github.com/eclipse-kuksa/kuksa-android-sdk/issues/78#issuecomment-1964220850_

**Comment by Chrylo** [comment]
Decided for a simple fix here. We can still think about introducing Hilt in another ticket.
