### ISSUE TITLE
Support the VSS 4.1 release

### ISSUE THREAD

**Issue by Chrylo** [eclipse-kuksa/kuksa-android-sdk#95]
**Is your feature request related to a problem? Please describe.**
The changes in the 4.1 currently break the VssNode model generation. 

**Describe the solution you'd like**

- Ensure downward compatibility 
- 4.1 Json + yaml files are correctly generating all necessary VssNode models

**Additional context**
https://github.com/COVESA/vehicle_signal_specification/releases

```
[ksp] java.lang.IllegalArgumentException: No default value found for kotlin.Any!
	at org.eclipse.kuksa.vssprocessor.spec.VssNodeSpecModel.getDefaultValue(VssNodeSpecModel.kt:96)
	at org.eclipse.kuksa.vssprocessor.spec.VssNodeSpecModel.createValueSpec(VssNodeSpecModel.kt:196)
	at org.eclipse.kuksa.vssprocessor.spec.VssNodeSpecModel.createClassSpec(VssNodeSpecModel.kt:117)
	at org.eclipse.kuksa.vssprocessor.VssModelGeneratorProcessor$VssDefinitionVisitor.generateModelFiles(VssModelGeneratorProcessor.kt:135)
	at org.eclipse.kuksa.vssprocessor.VssModelGeneratorProcessor$VssDefinitionVisitor.visitClassDeclaration(VssModelGeneratorProcessor.kt:102)
	at org.eclipse.kuksa.vssprocessor.VssModelGeneratorProcessor$VssDefinitionVisitor.visitClassDeclaration(VssModelGeneratorProcessor.kt:71)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSClassDeclarationImpl.accept(KSClassDeclarationImpl.kt:135)
	at org.eclipse.kuksa.vssprocessor.VssModelGeneratorProcessor.process(VssModelGeneratorProcessor.kt:65)
```

**Comment by erikbosch** [comment]
Is it possibly that `datatypeProperty` does not support `float[]` as datatype that cause the problem. The first signal using `float[]` was added to the standard catalog in VSS 4.1, but support for using arrays on all primitive types have been supported for a long time in VSS syntax. You could also consider adding support for `boolean[]` and `double[]` so that you support that in case a signal with that type would be added either in standard catalog or in a customer extension.

It could be worth noting that VSS syntax has added support for structs (see https://covesa.github.io/vehicle_signal_specification/rule_set/data_entry/data_types_struct/). This is not used in standard VSS catalog as of today and it will likely not enter the catalog in a while as support in various tools (including Kuksa) is limited or non-existing. But we could possibly think how we want to handle it, if we want a general handling if an "unsupported" type is found. Like if `datatypeProperty` return `Any`, then ignore that signal and print a warning in the log. Or simply just write an error and say "sorry, signal X with type Y is not supported, panic!" and refuse to continue. I.e. a well formatted error/warning rather than an exception.

**Comment by Chrylo** [comment]
Without a deeper look; yes that is most likely the case here. Also, like you mentioned we should handle the "else" branch differently because it will result into the above exception. 

<img width="874" alt="Screenshot 2024-03-13 at 15 48 40" src="https://github.com/eclipse-kuksa/kuksa-android-sdk/assets/1355532/35559ff1-50c4-4420-953e-515cc1235625">
